print("---PRIMER FRACCIONARIO--")
n1=int(input())
d1=int(input())
print("---SEGUNDO FRACCIONARIO--")
n2=int(input())
d2=int(input())
print("la suma entre la primera fraccion y la segunda es=",str(n1*d2+n2*d1),"/",str(d2*d1))
print("La resta entre la primera fraccion y la segunda es=",str(n1*d2-n2*d1),"/",str(d2*d1))
print("La multiplicacion entre la primera fraccion y la segunda es=",str(n1*n2),"/",str(d1*d2))
print("La division entre la primera fraccion y la segunda es=",str(n1*d2),"/",str(n2*d1))