from fractions import Fraction
print("---PRIMER FRACCIONARIO--")
n1=int(input())
d1=int(input())
print("---SEGUNDO FRACCIONARIO--")
n2=int(input())
d2=int(input())
f1=Fraction(n1,d1)
f2=Fraction(n2,d2)
print("la suma entre la primera fraccion y la segunda es=",f1+f2)
print("La resta entre la primera fraccion y la segunda es=",f1-f2)
print("La multiplicacion entre la primera fraccion y la segunda es=",f1*f2)
print("La division entre la primera fraccion y la segunda es=",f1/f2)